---
- name: Install and configure weatherapp
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: Run the equivalent of "apt-get update"
    apt:
      update_cache: yes

  - name: Setup nodejs source
    shell: curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

  - name: Install a list of packages
    apt:
      pkg:
      - nodejs

  - name: Toggle unzip package
    apt:
      name: unzip
      state: absent
